#!/bin/bash

echo "=== PRODUCTION MIGRATION FIX ==="
echo ""
echo "PROBLEM: Migration error - Table 'pengirimans' doesn't exist"
echo "SOLUTION: Fresh migration with clean tables"
echo ""
echo "Step 1: RESET ALL MIGRATIONS"
echo "php artisan migrate:fresh"
echo ""
echo "Step 2: RUN NEW MIGRATIONS"
echo "php artisan migrate"
echo ""
echo "Step 3: VERIFY TABLES"
echo "php artisan tinker --execute=\"print_r(DB::select('SHOW TABLES'))\""
echo ""
echo "=== ALTERNATIVE IF FRESH NOT WORKING ==="
echo "Step 1: Drop problematic tables manually"
echo "php artisan tinker --execute=\"DB::statement('DROP TABLE IF EXISTS pengirimans'); DB::statement('DROP TABLE IF EXISTS reviews');\""
echo ""
echo "Step 2: Clear migration cache"
echo "php artisan migrate:reset"
echo ""
echo "Step 3: Run migrations"
echo "php artisan migrate"
echo ""
echo "=== AFTER SUCCESS ==="
echo "Test pengiriman functionality"
echo "Test rating functionality"
echo "Verify data storage"
echo ""
echo "Migration files created:"
echo "- 2026_01_27_133937_create_pengirimans_table.php"
echo "- 2026_01_27_134645_create_reviews_table.php"
echo ""
echo "Tables will be created with:"
echo "- pengirimans: id, pesanan_id, nama_penerima, notelp_penerima, email, alamat_penerima, kabupaten, kecamatan, kab_id, kec_id, tgl_pengiriman, catatan, timestamps"
echo "- reviews: id, user_id, store_id, rating, ulasan, timestamps"
